---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blogarchive
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: telliott.io
    http:
      paths:
      - path: /node/
        backend:
          serviceName: blogarchive
          servicePort: http
      - path: /2015/
        backend:
          serviceName: blogarchive
          servicePort: http
      - path: /2016/
        backend:
          serviceName: blogarchive
          servicePort: http
      - path: /2017/
        backend:
          serviceName: blogarchive
          servicePort: http
      - path: /blogarchive
        backend:
          serviceName: blogarchive
          servicePort: http
{%- for i in (2..26) %}
      - path: /page{{i}}
        backend:
          serviceName: blogarchive
          servicePort: http
{%- endfor -%}