---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogarchive
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: telliott.io
    http:
      paths:
      - path: /node/
        backend:
          service:
              name: blogarchive
              port:
                name: http
      - path: /2015/
        backend:
          service:
              name: blogarchive
              port:
                name: http
      - path: /2016/
        backend:
          service:
              name: blogarchive
              port:
                name: http
      - path: /2017/
        backend:
          service:
              name: blogarchive
              port:
                name: http
      - path: /blogarchive
        backend:
          service:
              name: blogarchive
              port:
                name: http
{%- for i in (2..26) %}
      - path: /page{{i}}
        backend:
          service:
              name: blogarchive
              port:
                name: http
{%- endfor -%}